Revert "usb: gadget: configfs: Fix missing spin_lock_init()"
../drivers/usb/gadget/configfs.c:1749:22: error: no member named 'spinlock' in 'struct gadget_info'
        spin_lock_init(&gi->spinlock);
                        ~~  ^
../include/linux/spinlock.h:311:17: note: expanded from macro 'spin_lock_init'
        spinlock_check(_lock);                          \
                       ^~~~~
../drivers/usb/gadget/configfs.c:1749:22: error: no member named 'spinlock' in 'struct gadget_info'
        spin_lock_init(&gi->spinlock);
                        ~~  ^
../include/linux/spinlock.h:312:23: note: expanded from macro 'spin_lock_init'
        raw_spin_lock_init(&(_lock)->rlock);            \
                             ^~~~~
../include/linux/spinlock.h:105:9: note: expanded from macro 'raw_spin_lock_init'
        do { *(lock) = __RAW_SPIN_LOCK_UNLOCKED(lock); } while (0)
               ^~~~
2 errors generated.